### ISSUE TITLE
Homepage - Sidebar: Redundant profile name displayed on facebook widget in IE 7.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#100]
Inconsistency display compared to other browsers

![image](https://cloud.githubusercontent.com/assets/11186304/6704536/0e75b6a0-cd85-11e4-9d17-354a8d9ec7e5.png)

**Comment by christiancebudigital** [comment]
This is a bug from Facebook API, we have no control over this kind of issue.. this is 3rd party plug in.. ive also consulted Leoman regarding this issue.. and replied this is really a bug facebook and we have no control on fixing this.
