### ISSUE TITLE
Artists single page - Sidebar: Facebook widget gets distorted in IE 7.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#111]
![image](https://cloud.githubusercontent.com/assets/11186304/6705402/963bf216-cd8f-11e4-8882-7b3354c12f3d.png)

**Comment by christiancebudigital** [comment]
This is a bug from Facebook API, we have no control over this kind of issue.. this is 3rd party plug in.. ive also consulted Leoman regarding this issue.. and replied this is really a bug facebook and we have no control on fixing this.
