### ISSUE TITLE
Artists single page: 'View More Artists Work' button and thumbnail images should be shown always in the page as this has been filled-in pagelink at the backend.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#115]
![image](https://cloud.githubusercontent.com/assets/11186304/6705629/bd57c404-cd91-11e4-8798-733d487e5543.png)

**Comment by christiancebudigital** [comment]
![Uploading a.png . . .]()

**Comment by christiancebudigital** [comment]
![a](https://cloud.githubusercontent.com/assets/11186331/6722263/eabbc276-ce11-11e4-9c33-035705fb1245.png)
PLease clear your Cache.. this is what mine looks like on my end..

**Comment by maluzynel** [comment]
Mini galleries and 'View' button won't display in the page once featured image is not available.
