### ISSUE TITLE
All pages - Sidebar: Instagram widget should have display 'Sacred Tattoos' account instead of '@TitanUser'.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#117]
Since you have needed the client's account username and password, can you please provide documentation or steps on how to manage the Instagram user account to the client's end at the backend CMS.

As per our convo with Leoman, Instagram user account should be implemented dynamically so it can be manage easily by the client at the backend.

![image](https://cloud.githubusercontent.com/assets/11186304/6745533/1e59b34a-cef3-11e4-8da8-a3de9162845f.png)

**Comment by christiancebudigital** [comment]
Steps:
1. login as admin 
2. left sidebar click Instagram Feed
3. Click login instagram account
4. you there you will be redirected to a page where you can get you access token and user ID
5. after you got your access token and user id, input it to the field that was required on you instagram widget.
6. save changes,
note: you can also customize yout instagram by the tabs displayed in the plugin.
![insta](https://cloud.githubusercontent.com/assets/11186331/6745663/6bf57f38-cef5-11e4-9f3a-1fed2254c618.jpg)
