### ISSUE TITLE
Banner section: The cross image overlay should slightly move down exactly below the navigation menu section as per design specs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#12]
![image](https://cloud.githubusercontent.com/assets/11186304/6553091/f44c0490-c687-11e4-8f80-ee72e5bf2355.png)

**Comment by christiancebudigital** [comment]
Your Comparing 2 different  pages, homepage implementation is  moved down below the navigation.. innerpage implementation cross image is overlapped, this is just based on the design, what will you recommend?

**Comment by maluzynel** [comment]
Both designs should be implemented on specific pages. Homepage banner layout is different to inner pages. This has been implemented. Issue is now resolved.
