### ISSUE TITLE
Admin - Business details plugin: Redundancy information filled-in on Phone, Mobile and Fax phone numbers.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#13]
![image](https://cloud.githubusercontent.com/assets/11186304/6567782/60400ce8-c708-11e4-80a1-c030bd611033.png)

**Comment by christiancebudigital** [comment]
Dynamic Information, Design brief  provided only 1 contact number which is  9336 6111
