### ISSUE TITLE
Gallery page: Please make the gallery thumbnails display even number per page in mobile devices view.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#133]
iPad air

Suggestion: Better to remove 1 row line of thumbnail images in desktop view to make even number display in mobile devices view especially in iPad landscape view.

![image](https://cloud.githubusercontent.com/assets/11186304/6749000/d647aa2e-cf26-11e4-95cf-a760f65878b2.png)

**Comment by maluzynel** [comment]
Any response?

**Comment by christiancebudigital** [comment]
This is bootstrap auto adjust center, basically ngggallery displays,16 and when resizing the bootstraps adjust its content to make the gallery look good.

**Comment by maluzynel** [comment]
Suggestion: Better to remove 1 row grid line of thumbnail images in desktop view to make even number display in mobile devices view especially in iPad landscape view to look more good.

**Comment by christiancebudigital** [comment]
please verify
