### ISSUE TITLE
Artists page - Sidebar Leadins: Hover state gets distorted in iPad device view.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#145]
![image](https://cloud.githubusercontent.com/assets/11186304/6793755/442f936e-d204-11e4-9111-3cc40873ecf6.png)

**Comment by maluzynel** [comment]
Not yet fixed

**Comment by maluzynel** [comment]
Still misaligned in IE 7

![image](https://cloud.githubusercontent.com/assets/11186304/6794863/d1d518de-d212-11e4-9796-cb4285bdb8a0.png)

**Comment by maluzynel** [comment]
Gets misaligned in IE 8-10. please fix

**Comment by christiancebudigital** [comment]
please verify

**Comment by maluzynel** [comment]
Still misaligned in IE brower

![image](https://cloud.githubusercontent.com/assets/11186304/6795370/bc261806-d219-11e4-99e0-940c7d355e65.png)

**Comment by maluzynel** [comment]
IE browser default 11 still misaligned

![image](https://cloud.githubusercontent.com/assets/11186304/6795455/f82af316-d21a-11e4-87ff-0ac3a608fd41.png)

**Comment by christiancebudigital** [comment]
please verify..
