### ISSUE TITLE
Gallery page: Gallery thumbnail alignments gets broken.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#153]
![image](https://cloud.githubusercontent.com/assets/11186304/6796078/ed4165c8-d226-11e4-9fde-f48875037e57.png)

**Comment by maluzynel** [comment]
Should have 4 columns 3 rows display per page.

**Comment by christiancebudigital** [comment]
this can be done in gallery page settings..
