### ISSUE TITLE
Homepage - Content section: Heading title should have 29px font size as per mockup design.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#31]

**Comment by christiancebudigital** [comment]
Heading title is 35px

**Comment by maluzynel** [comment]
I mean it shoud be 29px font size.

**Comment by maluzynel** [comment]
Font size is not yet updated.

**Comment by maluzynel** [comment]
Heading title font size in the Homepage should be 29px as per design specs.

**Comment by christiancebudigital** [comment]
please clear your cache it is working on my end.
