### ISSUE TITLE
Inner pages - Sidebar: Three boxes should be from leadins custom posts. Currently unable to change the image and text. 

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#43]
![image](https://cloud.githubusercontent.com/assets/11186304/6589759/4d2080e2-c7e0-11e4-8a50-0639ee42172c.png)

**Comment by christiancebudigital** [comment]
You can edit sidebar, by choosing leadins in dashboard.., you can choose page link as per instructions.
