### ISSUE TITLE
Artists single pages: Featured image and mini galleries sizes should match up to the design specs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#47]
![image](https://cloud.githubusercontent.com/assets/11186304/6589799/6fc5d52e-c7e1-11e4-9c64-751263159245.png)

**Comment by christiancebudigital** [comment]
we used ACF for this single custom post images are dynamic, as for breadcrumbs.. we followed titan standards on breadcrumbs..

**Comment by maluzynel** [comment]
Alignments and sizes are not yet fixed in IE 7.
![image](https://cloud.githubusercontent.com/assets/11186304/6661464/ad11a2be-cbe7-11e4-8181-d187028506ac.png)

**Comment by maluzynel** [comment]
Inconsistent sizes in IE 7. Please also remove the red border style on the thumbnail images
![image](https://cloud.githubusercontent.com/assets/11186304/6703174/47c35560-cd72-11e4-85ef-65a7ba257a15.png)

**Comment by maluzynel** [comment]
Inconsistent featured size in IE 7 compared to the other browsers.

**Comment by maluzynel** [comment]
Gap spacing in between thumbnail images in IE7 doesn't match up the design specs and inconsistency compared to the other browsers.
