### ISSUE TITLE
Artists single pages: Thumbnail images empty rows at the backend should not be displayed on frontend.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#48]
![image](https://cloud.githubusercontent.com/assets/11186304/6589831/db11eec6-c7e1-11e4-9643-217b2d6d10f7.png)

**Comment by christiancebudigital** [comment]
conditional statement.. if no images were added on thumb img  but has title single page thumb images will not display.. but if no title but have uploaded an image.. single page thumb images  will display.

**Comment by maluzynel** [comment]
Title field is useless doesn't display on the image.
