### ISSUE TITLE
Artists single pages: Button for 'View more Artists works' is missing in the page.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#49]
![image](https://cloud.githubusercontent.com/assets/11186304/6589853/409ea496-c7e2-11e4-9423-fe1901113097.png)

**Comment by christiancebudigital** [comment]
Back end part.. Single custom post type artist - Input url link of artist work, if no artist work link provided just leave it blank.

**Comment by maluzynel** [comment]
Is this an internal or external link? If the button is for internal link only, better use pagelink option field listed all the pages.
