### ISSUE TITLE
Gallery page: Error album templates added at the backend.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#60]
![image](https://cloud.githubusercontent.com/assets/11186304/6590807/f0112002-c7f1-11e4-9fe0-3ab8d48dd44d.png)

**Comment by christiancebudigital** [comment]
this is not a bug, user error, you need to choose a gallery for your album..

**Comment by maluzynel** [comment]
Yes, I've followed the correct process but it shows error icon. This is now fixed.
