### ISSUE TITLE
All pages: Page should not be draggable on responsive view.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#73]
iPad 2

![Uploading image.png . . .]()

**Comment by christiancebudigital** [comment]
working on my end, please provide screenshot..

**Comment by maluzynel** [comment]
This has been fixed. 
![image](https://cloud.githubusercontent.com/assets/11186304/6661777/0d9725aa-cbed-11e4-988d-3307666bae87.png)
