### ISSUE TITLE
Menu button: Add hover and active style to the menu items.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#76]
![image](https://cloud.githubusercontent.com/assets/11186304/6591988/a780a298-c802-11e4-8e2e-69ef260e350d.png)

**Comment by maluzynel** [comment]
Active state should apply on menu items.

**Comment by christiancebudigital** [comment]
please clear cache working on my end..

**Comment by maluzynel** [comment]
Active state is different from hover state. Currently the homepage is open therefore Home menu should have highlighted.

![image](https://cloud.githubusercontent.com/assets/11186304/6703306/b1c8e554-cd74-11e4-8549-897477168aa8.png)
