### ISSUE TITLE
Artists page: Artists posts should be in three columns as there's still enough space on the right side.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#77]
iPad air

![image](https://cloud.githubusercontent.com/assets/11186304/6592019/f284fce4-c802-11e4-82f8-ff2843252813.png)

**Comment by maluzynel** [comment]
Not yet fixed on iPad Landscape view.

**Comment by christiancebudigital** [comment]
please clear your cache in ipad
