### ISSUE TITLE
Leadins section: Post items should be based from the Leadins custom posts, currently not.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#84]
![image](https://cloud.githubusercontent.com/assets/11186304/6661080/3365289c-cbe1-11e4-8e27-1833427b1ded.png)

**Comment by christiancebudigital** [comment]
Post items should are based from the Leadins custom posts, show only when Our artist, Our services and Gallery are present on leadins.

**Comment by maluzynel** [comment]
Homepage leadins are not yet based on Leadins custom posts and menu ordering.
