### ISSUE TITLE
Gallery page: Add hover state to the thumbnail images as per design specs.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#87]
![image](https://cloud.githubusercontent.com/assets/11186304/6661679/77636838-cbeb-11e4-9e54-8022e0ea6141.png)

**Comment by maluzynel** [comment]
The thumbnail images size doesn't match up to the design specs and the hover style gets overlapped.
![image](https://cloud.githubusercontent.com/assets/11186304/6703467/211ff72e-cd77-11e4-8a90-50773e965cfb.png)

**Comment by christiancebudigital** [comment]
![hovered](https://cloud.githubusercontent.com/assets/11186331/6726028/9e7983a4-ce4c-11e4-8d23-a8ca34597db5.jpg)

hovered and my end..

**Comment by maluzynel** [comment]
Thumbnail sizes should match up to the mockup design.

**Comment by maluzynel** [comment]
IE 7 doesn't have consistent gap spacing between rows thumbnail images compared to other browsers.

![image](https://cloud.githubusercontent.com/assets/11186304/6747411/f1ce4130-cf13-11e4-94ee-51b47f882175.png)
