### ISSUE TITLE
Admin - Forms: Send to Email value under Forms notification settings should be an email address as per standard.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#9]
![image](https://cloud.githubusercontent.com/assets/11186304/6552925/037ba292-c686-11e4-9462-6706a352d33b.png)

**Comment by maluzynel** [comment]
Please use the contact email specified on the design brief.

**Comment by christiancebudigital** [comment]
Based on the new standards on KB https://knowledgebase.titanweb.com.au/implementation-practices/gravity-forms/form-notification-email, anyways email already changed.
