### ISSUE TITLE
Homepage - Leadins section: Three boxes are not properly aligned, inconsistent alignment in different browsers.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#93]
Steps to replicate:
1. Try to check the leadin posts randomly with and without featured image, alignment gets broken.

Expected:
The dimension size should be consistent with or without featured image.

![image](https://cloud.githubusercontent.com/assets/11186304/6703900/c44b7450-cd7c-11e4-9d5c-fc9b9ec0decb.png)

**Comment by christiancebudigital** [comment]
ie7 alignment are properly aligned on my end...

**Comment by maluzynel** [comment]
Inconsistent sizes upon changing the menu ordering attributes of post items.

![image](https://cloud.githubusercontent.com/assets/11186304/6744764/3471ab5c-cee8-11e4-817b-807e2f54f8ba.png)
