### ISSUE TITLE
Footer section: Misaligned Titandigital text and logo in IE 7.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#96]
![image](https://cloud.githubusercontent.com/assets/11186304/6704351/22af908a-cd82-11e4-85f7-76bfec7ed4c2.png)

**Comment by maluzynel** [comment]
Not yet fixed in IE 7.. If you noticed the right alignment from the header section phone number to main menus, content section container and down to the footer section the alignment are not consistent compared to the other browsers and mockup design.

**Comment by christiancebudigital** [comment]
please check your version of ie.. this is fixed on my end...
![test](https://cloud.githubusercontent.com/assets/11186331/6746812/a7cac9be-cf09-11e4-9765-dcca3d3f91c8.jpg)

**Comment by maluzynel** [comment]
Sections are not properly aligned in IE 7 compared to the other browsers and mockup designs.

![image](https://cloud.githubusercontent.com/assets/11186304/6747561/1290f65e-cf16-11e4-94d9-b456bb0ab04a.png)

![image](https://cloud.githubusercontent.com/assets/11186304/6747557/fdc2c2b6-cf15-11e4-9cd0-5028f7595c49.png)
