### ISSUE TITLE
Homepage - Sidebar: Sacred Tattoos account should be displayed on the Instagram widget.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/Sacred-Tattoos#98]
3 Columns and 4 rows of image should filled-in.

![image](https://cloud.githubusercontent.com/assets/11186304/6704469/2460c2a8-cd84-11e4-9589-8c3d02a3ec60.png)

**Comment by christiancebudigital** [comment]
we need a username password of the owner on instagram account.. as of now, we currently use titan test account on instagram for text purpose.. once we have the account we can simply set the account name to on the site.
